In [26]:
#coding=utf-8
# https://mp.weixin.qq.com/s/uthpSrJIJQEpiU6g6z5FBg
import numpy as np

class fab():

    def __init__(self):
        self.his = [1,1]

    def __getitem__(self, n):
        while len(self.his) < n:
            length = len(self.his)
            self.his.append(self.his[length-1]+self.his[length-2])
        return self.his[n-1]

    def __str__(self):
        return str(",".join([str(x) for x in self.his]))

f = fab()
print(f[8])
print(f)


21
1,1,2,3,5,8,13,21


In [36]:
#    2
#   3 4
#  6 5 7
# 4 1 8 3

class Path():
    
    def __init__(self, items):
        self.items = np.array(items)
        self.history = [[0, 0, items[0][0]]] # [i,j,value]
        print(self.history)

    def path(self):
        n = 0
        while n < self.items.shape[0]-1:
            n += 1
            index_i =  self.history[n-1][1]
            self.history.append(
                [n, index_i, self.items[n][index_i]]
                if self.items[n][index_i] < self.items[n][index_i+1]
                else [n, index_i+1, self.items[n][index_i+1]]
            )
        return self.history


x = [[2,0,0,0],[3,4,0,0],[6,5,7,0],[4,1,8,3]]
p = Path(x)
print(p.path())


[[0, 0, 2]]
[[0, 0, 2], [1, 0, 3], [2, 1, 5], [3, 1, 1]]


In [1]:
# 硬币题: 求找零最少硬币个数，否则返回-1
coins = [1,2,5]
amount = 11


def solve(amount, coins):
    path = np.array([[amount]])

    def stop(path_n):
        flag = False
        for x in path_n:
            if x<0 or x in [1, 2, 5]:
                flag = True
                break
        return flag

    while stop(path[path.shape[0]]):
        next_layer = []
        for x in path[path.shape[0]]:
            

SyntaxError: unexpected EOF while parsing (<ipython-input-1-a8e06167ada7>, line 20)

In [22]:
# 矩阵链乘问题
# 问题描述：给定矩阵链 A_1*A_2*A_3...A_n, 求乘积最少乘法量, 记矩阵维度为 {p_0, p_1, ... p_n} 共n+1个维度
# 递归分析解的种类： 括号化结构特征解法——Catalan数 C_n = C_0*C_n + C_1*C_n-1 + ... + C_n*C_0 = 组合数(n,2n) / (n+1)
# (1) 最优子结构: 对于任一个子序列 A_i*A_i+1*...A_j, 以k为分分界点，最优代价 C_i,j=C_i,k+ C_k+1,j + p_i-1*p_k*p_j, 子序列要求也是最优代价
# (2) 子问题重叠性: 子结构共有 组合数(2,n)个i,j + n个划分点k = o(n**2)，递归时，低纬度子结构最优解被重复调用，综上可以用带备忘录的自底向上的表格法解决
# (3) 构造方法: 表m[1...n, 1...n]中m[i,j]记录子序列A_i,j的代价，表s[1..n-1, 2..n]中s[i,j]记录m[i,j]对应的分割点k

import numpy as np

# n+1 个矩阵维度，A_i矩阵的维度=p_i*p_i+1
p = [30,35,15,5,10,20,25]

def matrix_chain_order(p):
    # o(n**3)
    n = len(p)-1 # 6
    m, s = -1*np.ones((n,n)), -1*np.ones((n,n))
    for i in range(n):
        m[i,i] = 0

    for l in range(2, n+1): # l is the chain length 2 to 6
        for i in range(n-l+1): # 0 to 4
            j = i + l - 1
            for k in range(i, j): # i to j-1
                q = m[i,k] + m[k+1,j] + p[i]*p[k+1]*p[j+1]
                
                print(i, l, j, k, q)

                if q<m[i,j] or m[i,j]<0:
                    m[i,j] = q
                    s[i,j] = k
    
    return m, s

m, s = matrix_chain_order(p)      

s = s.astype(np.int16)
print(s)
    
def best_path(s, i, j):
    if i==j:
        return 'A_%s'%(str(i))
    
    return '(%s %s)'%(best_path(s,i,s[i,j]), best_path(s,s[i,j]+1, j))

print(best_path(s, 0, 5))
    




0 2 1 0 15750.0
1 2 2 1 2625.0
2 2 3 2 750.0
3 2 4 3 1000.0
4 2 5 4 5000.0
0 3 2 0 7875.0
0 3 2 1 18000.0
1 3 3 1 6000.0
1 3 3 2 4375.0
2 3 4 2 2500.0
2 3 4 3 3750.0
3 3 5 3 6250.0
3 3 5 4 3500.0
0 4 3 0 14875.0
0 4 3 1 21000.0
0 4 3 2 9375.0
1 4 4 1 13000.0
1 4 4 2 7125.0
1 4 4 3 11375.0
2 4 5 2 5375.0
2 4 5 3 9500.0
2 4 5 4 10000.0
0 5 4 0 28125.0
0 5 4 1 27250.0
0 5 4 2 11875.0
0 5 4 3 15375.0
1 5 5 1 18500.0
1 5 5 2 10500.0
1 5 5 3 18125.0
1 5 5 4 24625.0
0 6 5 0 36750.0
0 6 5 1 32375.0
0 6 5 2 15125.0
0 6 5 3 21875.0
0 6 5 4 26875.0
[[-1  0  0  2  2  2]
 [-1 -1  1  2  2  2]
 [-1 -1 -1  2  2  2]
 [-1 -1 -1 -1  3  4]
 [-1 -1 -1 -1 -1  4]
 [-1 -1 -1 -1 -1 -1]]
((A_0 (A_1 A_2)) ((A_3 A_4) A_5))
